### ISSUE TITLE
10_gpg-setup-part1.md. mount | grep hush gives ro access

### ISSUE THREAD

**Issue by ronpunz** [19hundreds/risks-workflow#3]
SSL key creation

I don't want to remember Joe's GPG passphrase and I'm happy to use openssl to store the passphrase (encrypted with AES 256) next to the coffin key inside the hush-partition.

I check that the sdcard is mounted:

mount | grep hush

Output:

    /dev/mapper/hush on /home/user/.hush type ext4 (rw,relatime,data=ordered) /dev/mapper/hush on /rw/home/user/.hush type ext4 (rw,relatime,data=ordered)

**_My Output gives read only access i.e.
 /dev/mapper/hush on /home/user/.hush type ext4 (ro,relatime,data=ordered) /dev/mapper/hush on /rw/home/user/.hush type ext4 (ro,relatime,data=ordered)_**
Can you suggest a solution?

**Comment by 19hundreds** [comment]
The encrypted sdcard partition is mounted RO by default mostly to protect the sdcard itself from accidents (like removing the sdcard while it's mounted).

When you need to mount the sdcard with RW access simply:

    risks rw hush

Then back to RO

    risks ro hush

I'm pretty sure I forgot to mention this in `risks -h`
